#pragma kernel CSMain
#pragma kernel CSMain_S

Texture3D<float4> noise;
RWTexture2D<float4> Result;
int layer;

[numthreads(32,32,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	uint3 pos = uint3(id.x, id.y, layer);
	Result[id.xy] = noise[pos];
}

Texture3D<float> noise_s;
RWTexture2D<float> Result_s;

[numthreads(32,32,1)]
void CSMain_S (uint3 id : SV_DispatchThreadID)
{
	uint3 pos = uint3(id.x, id.y, layer);
	Result_s[id.xy] = noise_s[pos];
}
